
export default {
  SERVER_URL: 'https://vseexpo.ru',
  CITY_LIST_URL: '/m/citylist/',
  COUNTRY_LIST_URL: '/m/countrylist/',
  SERVICE_LIST_URL: '/m/servicelist/',
  SERVICE_LIST_SAVE_URL: '/m/servicelist/save/',
  PROFESSION_LIST_URL: '/m/professionlist/',
  PROFESSION_LIST_SAVE_URL: '/m/professionlist/save/',
  SELECTIONPARAMETERS_URL: '/m/selectionparameters/',
  WORKERSEARCH_URL: '/worker/m/search/',
  JOB_LIST_URL: '/jobs/',
  MESSAGES_LIST_URL: '/messages/',
  PROFESSIONANDGROUPS_URL: '/m/professionandgroups/',
  LOGIN_URL: '/accounts/login/',
  REGISTER_URL: '/accounts/signup/',
  TEST_URL: 'https://vseexpo.ru/worker/testcsrf/',
  SETTINGS_URL: '/worker/m/settings/',
  SAVESETTINGS_URL: '/worker/settings/save/',
  PRIVACY_POLICY_URL: '/privacy-policy/',
  COMPANY_LIST_URL: '/companys/',
  DIALOG_LIST_URL: '/dialogs/',
  CHECK_LOGIN_URL: '/m/checklogin/',
  MESSAGE_SEND_URL: '/messages/send/',
};
